name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          runTests: false
      - run: yarn test
      - uses: cypress-io/github-action@v2
        with:
          install: false
          start: yarn dev
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          path: |
            cypress/videos
            cypress/integration/__image_snapshots__
      - run: yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEGAKIA }}"
          channelId: live
          projectId: tegakia
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
